import {
  AlertCircle,
  AlertTriangle,
  AlignLeft,
  Bell,
  BellRing,
  Calendar,
  CheckCircle2,
  CheckCheck,
  CheckSquare,
  ChevronsUpDown,
  CircleDot,
  CircleUserRound,
  ClipboardList,
  Columns3,
  Cookie,
  FolderOpen,
  Frame,
  Gauge,
  Hash,
  Layers,
  Lightbulb,
  List,
  ListFilter,
  Loader2,
  Menu,
  MessageSquare,
  MousePointerClick,
  PanelTop,
  RectangleEllipsis,
  Sparkles,
  Tag,
  TextCursorInput,
  ToggleRight,
  Type,
  XCircle,
} from "lucide-react";

export const COMPONENTS_CATALOG = [
  {
    id: "button",
    name: "Button",
    icon: MousePointerClick,
    description: "Primary and secondary actions with hover, focus and glow states.",
  },
  {
    id: "card",
    name: "Card",
    icon: PanelTop,
    description: "Content container with image placeholder, title, description and CTA.",
  },
  {
    id: "navbar",
    name: "Navbar",
    icon: Menu,
    description: "Site header with logo, navigation links and a call to action.",
  },
  {
    id: "input",
    name: "Input field",
    icon: TextCursorInput,
    description: "Labelled text field with placeholder, hint and focus ring.",
  },
  {
    id: "badge",
    name: "Badge / Tag",
    icon: Tag,
    description: "Small pills for statuses, versions and labels.",
  },
  {
    id: "modal",
    name: "Modal",
    icon: Frame,
    description: "Overlay dialog with trigger, blurred backdrop and close button.",
  },
  {
    id: "accordion",
    name: "Accordion",
    icon: ChevronsUpDown,
    description: "Three expandable sections that collapse smoothly.",
  },
  {
    id: "tooltip",
    name: "Tooltip",
    icon: MessageSquare,
    description: "Contextual hint bubble revealed on hover with an arrow.",
  },
  {
    id: "tabs",
    name: "Tabs",
    icon: Layers,
    description: "Segmented control switching between three content panels.",
  },
  {
    id: "dropdown",
    name: "Dropdown menu",
    icon: List,
    description: "Trigger button opening a floating list of options.",
  },
  {
    id: "switch",
    name: "Toggle / Switch",
    icon: ToggleRight,
    description: "On-off control with an animated knob and glow.",
  },
  {
    id: "skeleton",
    name: "Skeleton loader",
    icon: RectangleEllipsis,
    description: "Card-shaped pulsing placeholders shown while content loads.",
  },
  {
    id: "toast",
    name: "Toast / Notification",
    icon: Bell,
    description: "Transient success and error messages with icons.",
  },
  {
    id: "progress",
    name: "Progress bar",
    icon: Gauge,
    description: "Animated fill with a live percentage label.",
  },
  {
    id: "avatar",
    name: "Avatar",
    icon: CircleUserRound,
    description: "Image or initials fallback with an online status dot.",
  },
  {
    id: "checkbox",
    name: "Checkbox",
    icon: CheckSquare,
    description: "Accessible toggle box with checked, indeterminate, disabled, and error states.",
  },
  {
    id: "radio-group",
    name: "Radio Group",
    icon: CircleDot,
    description: "Single-choice selection group with arrow key navigation and card variants.",
  },
  {
    id: "select",
    name: "Select",
    icon: ListFilter,
    description: "Accessible dropdown selector with placeholder, search, and disabled options.",
  },
  {
    id: "textarea",
    name: "Textarea",
    icon: AlignLeft,
    description: "Multi-line text input with character limit counter and auto-resize handling.",
  },
  {
    id: "form",
    name: "Form",
    icon: ClipboardList,
    description: "Form wrapper with submission handling, validation context, and error summaries.",
  },
  {
    id: "label",
    name: "Label",
    icon: Type,
    description: "Typography-aligned label with required indicator (*), optional badge, and hints.",
  },
  {
    id: "form-field",
    name: "Form Field",
    icon: Columns3,
    description: "Unified wrapper connecting label, control, helper text, and validation alerts.",
  },
  {
    id: "date-input",
    name: "Date Input",
    icon: Calendar,
    description: "Semantic date input with calendar trigger icon, clear action, and min/max limits.",
  },
  {
    id: "number-input",
    name: "Number Input",
    icon: Hash,
    description: "Stepper-controlled numeric input with increment (+), decrement (-), and arrow key steps.",
  },
  {
    id: "showcase",
    name: "Documentation & Showcase",
    icon: Sparkles,
    description: "Integrated form playground testing states, controls, and accessibility live.",
  },
  {
    id: "alert",
    name: "Alert / Banner",
    icon: AlertCircle,
    description: "Contextual banners with info, success, warning and destructive variants with dismiss.",
  },
  {
    id: "confirmation-dialog",
    name: "Confirmation Dialog",
    icon: CheckCheck,
    description: "Accessible modal dialog for verifying user actions with focus trap and loading states.",
  },
  {
    id: "alert-dialog",
    name: "Alert Dialog",
    icon: AlertTriangle,
    description: "Critical modal alert with safe cancel-first focus and role='alertdialog' semantics.",
  },
  {
    id: "loading-overlay",
    name: "Loading Overlay",
    icon: Loader2,
    description: "Interactive loading overlay with spinner, blocking interaction and status ARIA.",
  },
  {
    id: "empty-state",
    name: "Empty State",
    icon: FolderOpen,
    description: "Zero-data visual state with presets for searches, empty inboxes, and initial onboarding.",
  },
  {
    id: "error-state",
    name: "Error State",
    icon: XCircle,
    description: "Failure boundary with retry CTA, loading retry feedback, and technical details toggle.",
  },
  {
    id: "success-state",
    name: "Success State",
    icon: CheckCircle2,
    description: "Completion state with animated checkmark badge, key-value summary, and next actions.",
  },
  {
    id: "callout",
    name: "Callout",
    icon: Lightbulb,
    description: "Contextual editorial aside with left accent rule, tips, and dismissible actions.",
  },
  {
    id: "notification-center",
    name: "Notification Center",
    icon: BellRing,
    description: "Dropdown drawer with read/unread tracking, filter tabs, mark all read, and badge counters.",
  },
  {
    id: "cookie-banner",
    name: "Cookie Banner",
    icon: Cookie,
    description: "Consent management banner with granular category preferences and persistent storage.",
  },
] as const;

export type ComponentId = (typeof COMPONENTS_CATALOG)[number]["id"];
