import {
  Bell,
  ChevronsUpDown,
  CircleUserRound,
  Frame,
  Gauge,
  Layers,
  List,
  Menu,
  MessageSquare,
  MousePointerClick,
  PanelTop,
  RectangleEllipsis,
  Tag,
  TextCursorInput,
  ToggleRight,
} from "lucide-react";

export const COMPONENTS_CATALOG = [
  {
    id: "button",
    name: "Button",
    icon: MousePointerClick,
    description: "Primary and secondary actions with hover, focus and glow states.",
  },
  {
    id: "card",
    name: "Card",
    icon: PanelTop,
    description: "Content container with image placeholder, title, description and CTA.",
  },
  {
    id: "navbar",
    name: "Navbar",
    icon: Menu,
    description: "Site header with logo, navigation links and a call to action.",
  },
  {
    id: "input",
    name: "Input field",
    icon: TextCursorInput,
    description: "Labelled text field with placeholder, hint and focus ring.",
  },
  {
    id: "badge",
    name: "Badge / Tag",
    icon: Tag,
    description: "Small pills for statuses, versions and labels.",
  },
  {
    id: "modal",
    name: "Modal",
    icon: Frame,
    description: "Overlay dialog with trigger, blurred backdrop and close button.",
  },
  {
    id: "accordion",
    name: "Accordion",
    icon: ChevronsUpDown,
    description: "Three expandable sections that collapse smoothly.",
  },
  {
    id: "tooltip",
    name: "Tooltip",
    icon: MessageSquare,
    description: "Contextual hint bubble revealed on hover with an arrow.",
  },
  {
    id: "tabs",
    name: "Tabs",
    icon: Layers,
    description: "Segmented control switching between three content panels.",
  },
  {
    id: "dropdown",
    name: "Dropdown menu",
    icon: List,
    description: "Trigger button opening a floating list of options.",
  },
  {
    id: "switch",
    name: "Toggle / Switch",
    icon: ToggleRight,
    description: "On-off control with an animated knob and glow.",
  },
  {
    id: "skeleton",
    name: "Skeleton loader",
    icon: RectangleEllipsis,
    description: "Card-shaped pulsing placeholders shown while content loads.",
  },
  {
    id: "toast",
    name: "Toast / Notification",
    icon: Bell,
    description: "Transient success and error messages with icons.",
  },
  {
    id: "progress",
    name: "Progress bar",
    icon: Gauge,
    description: "Animated fill with a live percentage label.",
  },
  {
    id: "avatar",
    name: "Avatar",
    icon: CircleUserRound,
    description: "Image or initials fallback with an online status dot.",
  },
] as const;
