import {
  AlertCircle,
  AlertTriangle,
  AlignLeft,
  Bell,
  BellRing,
  Calendar,
  CheckCircle2,
  CheckCheck,
  CheckSquare,
  ChevronsUpDown,
  CircleDot,
  CircleUserRound,
  ClipboardList,
  Columns3,
  Cookie,
  FolderOpen,
  Frame,
  Gauge,
  Hash,
  Layers,
  Lightbulb,
  List,
  ListFilter,
  Loader2,
  Menu,
  MessageSquare,
  MousePointerClick,
  PanelTop,
  RectangleEllipsis,
  Sparkles,
  Tag,
  TextCursorInput,
  ToggleRight,
  Type,
  XCircle,
  ArrowUp,
  Command,
  Compass,
  ExternalLink,
  ListOrdered,
  Milestone,
  PanelLeft,
  Smartphone,
  Split,
  Waypoints,
  Clock,
  CalendarDays,
  LayoutGrid,
  MessageCircle,
  MousePointer,
  PanelRight,
  Plus,
  Search,
  Table as TableIcon,
  TableProperties,
  History,
  BarChart3,
  Star,
  AlignJustify,
  KeyRound,
  Grid3X3,
  SeparatorHorizontal,
  Box,
  Columns2,
  Ratio,
  ScrollText,
  GripVertical,
  GalleryVerticalEnd,
  PlayCircle,
  Activity,
  CircleDashed,
  Sparkle,
  Wifi,
  TextQuote,
  Percent,
  Cpu,
  ImageIcon,
  GalleryHorizontalEnd,
  Video,
  Headphones,
  Maximize,
  Clapperboard,
  Code2,
  FileType2,
  FileArchive,
  Filter as FilterIcon,
  ArrowUpDown,
  Palette,
  SlidersHorizontal,
  HelpCircle,
  AtSign,
  Smile,
  FileEdit,
  UploadCloud,
  FolderTree,
  Network,
  Workflow,
  CalendarRange,
  GanttChartSquare,
  GitGraph,
  GitMerge,
  MessagesSquare,
  Send,
  MoreHorizontal,
  GitCompare,
  Terminal,
  FileText,
  Braces,
  PhoneCall,
  Globe,
  Database,
  Crosshair,
  FunctionSquare,
  MapPin,
  ShieldCheck,
  Eye,
  FileJson,
  ShieldAlert,
  GitCommit,
  Keyboard,
  Languages,
} from "lucide-react";

export const COMPONENTS_CATALOG = [
  {
    id: "button",
    name: "Button",
    icon: MousePointerClick,
    description: "Primary and secondary actions with hover, focus and glow states.",
  },
  {
    id: "card",
    name: "Card",
    icon: PanelTop,
    description: "Content container with image placeholder, title, description and CTA.",
  },
  {
    id: "navbar",
    name: "Navbar",
    icon: Menu,
    description: "Site header with logo, navigation links and a call to action.",
  },
  {
    id: "input",
    name: "Input field",
    icon: TextCursorInput,
    description: "Labelled text field with placeholder, hint and focus ring.",
  },
  {
    id: "badge",
    name: "Badge / Tag",
    icon: Tag,
    description: "Small pills for statuses, versions and labels.",
  },
  {
    id: "modal",
    name: "Modal",
    icon: Frame,
    description: "Overlay dialog with trigger, blurred backdrop and close button.",
  },
  {
    id: "accordion",
    name: "Accordion",
    icon: ChevronsUpDown,
    description: "Three expandable sections that collapse smoothly.",
  },
  {
    id: "tooltip",
    name: "Tooltip",
    icon: MessageSquare,
    description: "Contextual hint bubble revealed on hover with an arrow.",
  },
  {
    id: "tabs",
    name: "Tabs",
    icon: Layers,
    description: "Segmented control switching between three content panels.",
  },
  {
    id: "dropdown",
    name: "Dropdown menu",
    icon: List,
    description: "Trigger button opening a floating list of options.",
  },
  {
    id: "switch",
    name: "Toggle / Switch",
    icon: ToggleRight,
    description: "On-off control with an animated knob and glow.",
  },
  {
    id: "skeleton",
    name: "Skeleton loader",
    icon: RectangleEllipsis,
    description: "Card-shaped pulsing placeholders shown while content loads.",
  },
  {
    id: "toast",
    name: "Toast / Notification",
    icon: Bell,
    description: "Transient success and error messages with icons.",
  },
  {
    id: "progress",
    name: "Progress bar",
    icon: Gauge,
    description: "Animated fill with a live percentage label.",
  },
  {
    id: "avatar",
    name: "Avatar",
    icon: CircleUserRound,
    description: "Image or initials fallback with an online status dot.",
  },
  {
    id: "checkbox",
    name: "Checkbox",
    icon: CheckSquare,
    description: "Accessible toggle box with checked, indeterminate, disabled, and error states.",
  },
  {
    id: "radio-group",
    name: "Radio Group",
    icon: CircleDot,
    description: "Single-choice selection group with arrow key navigation and card variants.",
  },
  {
    id: "select",
    name: "Select",
    icon: ListFilter,
    description: "Accessible dropdown selector with placeholder, search, and disabled options.",
  },
  {
    id: "textarea",
    name: "Textarea",
    icon: AlignLeft,
    description: "Multi-line text input with character limit counter and auto-resize handling.",
  },
  {
    id: "form",
    name: "Form",
    icon: ClipboardList,
    description: "Form wrapper with submission handling, validation context, and error summaries.",
  },
  {
    id: "label",
    name: "Label",
    icon: Type,
    description: "Typography-aligned label with required indicator (*), optional badge, and hints.",
  },
  {
    id: "form-field",
    name: "Form Field",
    icon: Columns3,
    description: "Unified wrapper connecting label, control, helper text, and validation alerts.",
  },
  {
    id: "date-input",
    name: "Date Input",
    icon: Calendar,
    description: "Semantic date input with calendar trigger icon, clear action, and min/max limits.",
  },
  {
    id: "number-input",
    name: "Number Input",
    icon: Hash,
    description: "Stepper-controlled numeric input with increment (+), decrement (-), and arrow key steps.",
  },
  {
    id: "showcase",
    name: "Documentation & Showcase",
    icon: Sparkles,
    description: "Integrated form playground testing states, controls, and accessibility live.",
  },
  {
    id: "alert",
    name: "Alert / Banner",
    icon: AlertCircle,
    description: "Contextual banners with info, success, warning and destructive variants with dismiss.",
  },
  {
    id: "confirmation-dialog",
    name: "Confirmation Dialog",
    icon: CheckCheck,
    description: "Accessible modal dialog for verifying user actions with focus trap and loading states.",
  },
  {
    id: "alert-dialog",
    name: "Alert Dialog",
    icon: AlertTriangle,
    description: "Critical modal alert with safe cancel-first focus and role='alertdialog' semantics.",
  },
  {
    id: "loading-overlay",
    name: "Loading Overlay",
    icon: Loader2,
    description: "Interactive loading overlay with spinner, blocking interaction and status ARIA.",
  },
  {
    id: "empty-state",
    name: "Empty State",
    icon: FolderOpen,
    description: "Zero-data visual state with presets for searches, empty inboxes, and initial onboarding.",
  },
  {
    id: "error-state",
    name: "Error State",
    icon: XCircle,
    description: "Failure boundary with retry CTA, loading retry feedback, and technical details toggle.",
  },
  {
    id: "success-state",
    name: "Success State",
    icon: CheckCircle2,
    description: "Completion state with animated checkmark badge, key-value summary, and next actions.",
  },
  {
    id: "callout",
    name: "Callout",
    icon: Lightbulb,
    description: "Contextual editorial aside with left accent rule, tips, and dismissible actions.",
  },
  {
    id: "notification-center",
    name: "Notification Center",
    icon: BellRing,
    description: "Dropdown drawer with read/unread tracking, filter tabs, mark all read, and badge counters.",
  },
  {
    id: "cookie-banner",
    name: "Cookie Banner",
    icon: Cookie,
    description: "Consent management banner with granular category preferences and persistent storage.",
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    icon: Milestone,
    description: "Semantic trail navigation with icons, custom separators, responsive collapse, and active page semantics.",
  },
  {
    id: "pagination",
    name: "Pagination",
    icon: ListOrdered,
    description: "Configurable page switcher with range ellipsis, first/last jumps, and mobile responsive controls.",
  },
  {
    id: "sidebar",
    name: "Sidebar",
    icon: PanelLeft,
    description: "Collapsible navigation drawer with nested submenus, mobile slide-out overlay, badges, and focus trap.",
  },
  {
    id: "navigation-menu",
    name: "Navigation Menu",
    icon: Compass,
    description: "Accessible site navigation with dropdown content panels, active state indicators, and keyboard arrows.",
  },
  {
    id: "menu-bar",
    name: "Menu Bar",
    icon: Split,
    description: "Application-grade horizontal menu bar with nested cascading submenus, shortcuts, and ARIA menubar semantics.",
  },
  {
    id: "stepper",
    name: "Stepper",
    icon: Waypoints,
    description: "Process wizard with completed checkmarks, current highlights, error states, and responsive orientation.",
  },
  {
    id: "bottom-navigation",
    name: "Bottom Navigation",
    icon: Smartphone,
    description: "Mobile app bottom dock with badge indicators, safe-area padding, and active destination markers.",
  },
  {
    id: "command-menu",
    name: "Command Menu",
    icon: Command,
    description: "Command palette modal with instant search filtering, keyboard roving focus, and shortcut triggers.",
  },
  {
    id: "link",
    name: "Link",
    icon: ExternalLink,
    description: "Polymorphic anchor with automatic external target/rel detection, visual underline styles, and focus rings.",
  },
  {
    id: "back-to-top",
    name: "Back to Top",
    icon: ArrowUp,
    description: "Floating action button with scroll threshold visibility, smooth scrolling animation, and accessible label.",
  },
  {
    id: "popover",
    name: "Popover",
    icon: MessageCircle,
    description: "Floating contextual panel anchored to a trigger with collision detection and focus management.",
  },
  {
    id: "context-menu",
    name: "Context Menu",
    icon: MousePointer,
    description: "Pointer-positioned right-click context menu with keyboard shortcuts, submenus, and boundary checks.",
  },
  {
    id: "hover-card",
    name: "Hover Card",
    icon: MessageSquare,
    description: "Supplementary preview popover with enter/leave delay throttling and keyboard focus support.",
  },
  {
    id: "drawer",
    name: "Drawer / Sheet",
    icon: PanelRight,
    description: "Sliding modal panel anchored to any viewport edge (left, right, top, bottom) with focus trap.",
  },
  {
    id: "command-palette",
    name: "Command Palette",
    icon: Search,
    description: "Quick launcher modal with category filtering, command descriptions, and keyboard navigation.",
  },
  {
    id: "date-picker",
    name: "Date Picker",
    icon: Calendar,
    description: "Interactive date selection input with calendar popup, today jump, and formatting.",
  },
  {
    id: "time-picker",
    name: "Time Picker",
    icon: Clock,
    description: "Configurable time input with hours, minutes, AM/PM stepper, and quick selection presets.",
  },
  {
    id: "calendar",
    name: "Calendar",
    icon: CalendarDays,
    description: "Monthly grid calendar with day states, month navigation, and accessible date labels.",
  },
  {
    id: "mega-menu",
    name: "Mega Menu",
    icon: LayoutGrid,
    description: "Enterprise-grade multi-column navigation menu with categorised columns and featured banners.",
  },
  {
    id: "floating-action-button",
    name: "Floating Action Button",
    icon: Plus,
    description: "Corner-docked primary action trigger with extended labels and expandable speed-dial actions.",
  },
  {
    id: "table",
    name: "Table",
    icon: TableIcon,
    description: "Semantic tabular data presentation with headers, alignments, and styled rows.",
  },
  {
    id: "data-table",
    name: "Data Table",
    icon: TableProperties,
    description: "Full-featured data table with live column sorting, search filtering, row selection, and pagination.",
  },
  {
    id: "list",
    name: "List",
    icon: List,
    description: "Interactive and bordered list layouts with leading icons, status indicators, and actions.",
  },
  {
    id: "timeline",
    name: "Timeline",
    icon: History,
    description: "Vertical chronological activity feed with status icons, connector lines, and timestamps.",
  },
  {
    id: "stat-card",
    name: "Stat / Metric Card",
    icon: BarChart3,
    description: "KPI metric display card with primary number, trend indicators, and supporting context.",
  },
  {
    id: "rating",
    name: "Rating",
    icon: Star,
    description: "Accessible interactive star rating with hover preview, half-star granularity, and keyboard controls.",
  },
  {
    id: "chip",
    name: "Chip",
    icon: Tag,
    description: "Compact filter and tag chips with interactive selection, avatars, and dismissible remove buttons.",
  },
  {
    id: "description-list",
    name: "Description List",
    icon: AlignJustify,
    description: "Semantic key-value pairs formatted as definition lists with horizontal and grid alignments.",
  },
  {
    id: "key-value-list",
    name: "Key-Value List",
    icon: KeyRound,
    description: "Metadata inspection list with monospace value formatting and instant clipboard copy buttons.",
  },
  {
    id: "data-grid",
    name: "Data Grid",
    icon: Grid3X3,
    description: "Spreadsheet-style 2D data matrix featuring roving tabindex and directional arrow-key cell navigation.",
  },
  {
    id: "collapsible",
    name: "Collapsible",
    icon: ChevronsUpDown,
    description: "Expandable disclosure section with smooth height transition and keyboard controls.",
  },
  {
    id: "divider",
    name: "Divider / Separator",
    icon: SeparatorHorizontal,
    description: "Visual separator for horizontal, vertical, labeled, and decorative content division.",
  },
  {
    id: "container",
    name: "Container",
    icon: Box,
    description: "Responsive centered wrapper with fluid width constraints and padding presets.",
  },
  {
    id: "grid",
    name: "Grid",
    icon: LayoutGrid,
    description: "CSS Grid layout primitive with responsive column configurations and auto-fit repeat.",
  },
  {
    id: "stack",
    name: "Stack",
    icon: Layers,
    description: "Flexbox linear layout primitive supporting horizontal, vertical, gap, and wrapping.",
  },
  {
    id: "split-pane",
    name: "Split Pane",
    icon: Columns2,
    description: "Two-panel layout with draggable separator, keyboard adjustment, and min/max limits.",
  },
  {
    id: "aspect-ratio",
    name: "Aspect Ratio",
    icon: Ratio,
    description: "Container maintaining fixed aspect proportions (16:9, 4:3, 1:1, 21:9) across screen sizes.",
  },
  {
    id: "scroll-area",
    name: "Scroll Area",
    icon: ScrollText,
    description: "Custom-styled scrollable view supporting directional overflow and keyboard focus.",
  },
  {
    id: "resizable-panel",
    name: "Resizable Panel",
    icon: GripVertical,
    description: "Multi-panel group with draggable resize handles, constraints, and touch support.",
  },
  {
    id: "masonry",
    name: "Masonry",
    icon: GalleryVerticalEnd,
    description: "Responsive Pinterest-style waterfall layout for variable-height cards and items.",
  },
  {
    id: "spinner",
    name: "Spinner / Loader",
    icon: Loader2,
    description: "Indeterminate SVG spinner with size variants, color themes, accessible status labels, and reduced-motion handling.",
  },
  {
    id: "loading-button",
    name: "Loading Button",
    icon: PlayCircle,
    description: "Interactive button with built-in spinner, loading label, duplicate-click prevention, and dimension stability.",
  },
  {
    id: "status-indicator",
    name: "Status Indicator",
    icon: Activity,
    description: "System status badge with color coding, animated pulse ping, accessible text labels, and semantic states.",
  },
  {
    id: "step-progress",
    name: "Step Progress",
    icon: ListOrdered,
    description: "Multi-step progress tracker with horizontal/vertical layouts, completed checks, and active step highlights.",
  },
  {
    id: "circular-progress",
    name: "Circular Progress",
    icon: CircleDashed,
    description: "Radial progress ring supporting determinate percentages, indeterminate spinning, and custom center content.",
  },
  {
    id: "shimmer",
    name: "Shimmer",
    icon: Sparkle,
    description: "Content placeholder with smooth gradient sweep animation, preserving layout geometry during data loads.",
  },
  {
    id: "connection-status",
    name: "Connection Status",
    icon: Wifi,
    description: "Network connectivity monitor indicating online, offline, reconnecting, and error states with latency tags.",
  },
  {
    id: "skeleton-text",
    name: "Skeleton Text",
    icon: TextQuote,
    description: "Text placeholder with configurable line count, typography-aligned heights, and realistic last-line tapering.",
  },
  {
    id: "loading-bar",
    name: "Loading Bar",
    icon: Percent,
    description: "Horizontal progress bar supporting determinate percentages, sliding indeterminate beams, and value labels.",
  },
  {
    id: "processing-indicator",
    name: "Processing Indicator",
    icon: Cpu,
    description: "Async operation state manager with active, success, error, and idle states, progress bars, and retry hooks.",
  },
  {
    id: "image",
    name: "Image",
    description: "Responsive image wrapper with loading and error states.",
    category: "Media & Content",
    icon: ImageIcon,
    isNew: true,
  },
  {
    id: "image-gallery",
    name: "Image Gallery",
    description: "A responsive grid layout for displaying a collection of images.",
    category: "Media & Content",
    icon: LayoutGrid,
    isNew: true,
  },
  {
    id: "carousel",
    name: "Carousel",
    description: "A simple horizontal scrolling carousel using CSS scroll snap.",
    category: "Media & Content",
    icon: GalleryHorizontalEnd,
    isNew: true,
  },
  {
    id: "video-player",
    name: "Video Player",
    description: "A responsive wrapper for HTML5 video with native controls.",
    category: "Media & Content",
    icon: Video,
    isNew: true,
  },
  {
    id: "audio-player",
    name: "Audio Player",
    description: "A styled wrapper for HTML5 audio playback.",
    category: "Media & Content",
    icon: Headphones,
    isNew: true,
  },
  {
    id: "lightbox",
    name: "Lightbox",
    description: "A modal overlay for viewing media in fullscreen mode.",
    category: "Media & Content",
    icon: Maximize,
    isNew: true,
  },
  {
    id: "media-card",
    name: "Media Card",
    description: "A specialized card designed for highlighting media content.",
    category: "Media & Content",
    icon: Clapperboard,
    isNew: true,
  },
  {
    id: "code-block",
    name: "Code Block",
    description: "Syntax highlighting wrapper with a copy to clipboard button.",
    category: "Media & Content",
    icon: Code2,
    isNew: true,
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "A basic safe markdown renderer returning React nodes.",
    category: "Media & Content",
    icon: FileType2,
    isNew: true,
  },
  {
    id: "file-preview",
    name: "File Preview",
    description: "A component to display file metadata with an optional download action.",
    category: "Media & Content",
    icon: FileArchive,
    isNew: true,
  },
  {
    id: "search-bar",
    name: "Search Bar",
    description: "Search input with suggestions, query clearing, loading feedback, and keyboard control.",
    category: "Advanced / Utility",
    icon: Search,
    isNew: true,
  },
  {
    id: "filter",
    name: "Filter",
    description: "Multi-type facet filtering toolbar with count indicators, reset actions, and responsive layout.",
    category: "Advanced / Utility",
    icon: FilterIcon,
    isNew: true,
  },
  {
    id: "sort-menu",
    name: "Sort Menu",
    description: "Dropdown selector for ordering datasets by ascending or descending fields with directional cues.",
    category: "Advanced / Utility",
    icon: ArrowUpDown,
    isNew: true,
  },
  {
    id: "range-slider",
    name: "Range Slider",
    description: "Dual-thumb slider track for selecting bounded interval minimums and maximums without handle overlap.",
    category: "Advanced / Utility",
    icon: SlidersHorizontal,
    isNew: true,
  },
  {
    id: "slider",
    name: "Slider",
    description: "Single-value continuous slider with touch dragging, step increments, and optional scale marks.",
    category: "Advanced / Utility",
    icon: SlidersHorizontal,
    isNew: true,
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Color selector with palette swatches, hex input validation, and native wheel integration.",
    category: "Advanced / Utility",
    icon: Palette,
    isNew: true,
  },
  {
    id: "combobox",
    name: "Combobox",
    description: "Autocomplete select menu with keyboard listbox navigation, option highlighting, and clear action.",
    category: "Advanced / Utility",
    icon: ChevronsUpDown,
    isNew: true,
  },
  {
    id: "multi-select",
    name: "Multi-Select",
    description: "Tag-based multiple selection component with chip removal, option filtering, and batch clear.",
    category: "Advanced / Utility",
    icon: CheckSquare,
    isNew: true,
  },
  {
    id: "otp-input",
    name: "OTP / PIN Input",
    description: "Segmented digit code input with auto-advance, backspace navigation, paste distribution, and masking.",
    category: "Advanced / Utility",
    icon: KeyRound,
    isNew: true,
  },
  {
    id: "faq",
    name: "FAQ Section",
    description: "Frequently asked questions accordion with category filters, live keyword search, and support CTA.",
    category: "Data Display",
    icon: HelpCircle,
    isNew: true,
  },
  {
    id: "command-button-group",
    name: "Command Button Group",
    description: "Group related actions with primary/secondary distinction, keyboard shortcuts, and responsive orientation.",
    category: "Actions & Rich Text",
    icon: Command,
    isNew: true,
  },
  {
    id: "button-group",
    name: "Button Group",
    description: "Connected buttons with shared borders, seamless rounded corners, and focus elevation.",
    category: "Actions & Rich Text",
    icon: Columns2,
    isNew: true,
  },
  {
    id: "split-button",
    name: "Split Button",
    description: "Primary action paired with a connected dropdown menu for secondary context actions.",
    category: "Actions & Rich Text",
    icon: Split,
    isNew: true,
  },
  {
    id: "segmented-control",
    name: "Segmented Control",
    description: "Interactive multi-option mode switcher with active pill indicator and full keyboard roving navigation.",
    category: "Actions & Rich Text",
    icon: ToggleRight,
    isNew: true,
  },
  {
    id: "toolbar",
    name: "Toolbar",
    description: "Compact responsive row of tools, toggle groups, and formatting buttons with overflow containment.",
    category: "Actions & Rich Text",
    icon: SlidersHorizontal,
    isNew: true,
  },
  {
    id: "floating-toolbar",
    name: "Floating Toolbar",
    description: "Contextual actions that float near selected content with collision detection and keyboard escape.",
    category: "Actions & Rich Text",
    icon: Sparkles,
    isNew: true,
  },
  {
    id: "rich-text-editor",
    name: "Rich Text Editor",
    description: "Feature-rich formatting editor supporting bold, lists, links, headings, blockquotes, and safe HTML sanitization.",
    category: "Actions & Rich Text",
    icon: FileEdit,
    isNew: true,
  },
  {
    id: "mention-input",
    name: "Mention Input",
    description: "Text input with trigger-based autocomplete popup for tagging users and team members.",
    category: "Actions & Rich Text",
    icon: AtSign,
    isNew: true,
  },
  {
    id: "emoji-picker",
    name: "Emoji Picker",
    description: "Searchable emoji picker with category tabs, recent history, and live preview.",
    category: "Actions & Rich Text",
    icon: Smile,
    isNew: true,
  },
  {
    id: "tag-editor",
    name: "Mention / Tag Editor",
    description: "Inline chip manager for adding, editing, validating, and removing tags and user mentions.",
    category: "Actions & Rich Text",
    icon: Tag,
    isNew: true,
  },
  {
    id: "file-upload-dropzone",
    name: "File Upload Dropzone",
    description: "Drag-and-drop file upload container with format validation, size guards, and file inspection.",
    category: "Files & Hierarchy",
    icon: UploadCloud,
    isNew: true,
  },
  {
    id: "file-upload-progress",
    name: "File Upload Progress List",
    description: "Multi-file transfer manager with progress tracking, pause/resume, retry, and client demo states.",
    category: "Files & Hierarchy",
    icon: Loader2,
    isNew: true,
  },
  {
    id: "file-manager",
    name: "File Manager",
    description: "Complete browser file explorer with folder navigation, search, grid/list modes, upload, and deletion.",
    category: "Files & Hierarchy",
    icon: FolderOpen,
    isNew: true,
  },
  {
    id: "folder-tree",
    name: "Folder Tree",
    description: "Collapsible directory navigation tree with nested hierarchy levels and folder item counts.",
    category: "Files & Hierarchy",
    icon: FolderTree,
    isNew: true,
  },
  {
    id: "tree-view",
    name: "Tree View",
    description: "Multi-level hierarchical data viewer with keyboard roving navigation, checkboxes, and badge support.",
    category: "Files & Hierarchy",
    icon: Network,
    isNew: true,
  },
  {
    id: "organization-chart",
    name: "Organization Chart",
    description: "Visual reporting structure and company hierarchy diagram with branch expand/collapse.",
    category: "Files & Hierarchy",
    icon: Workflow,
    isNew: true,
  },
  {
    id: "kanban-board",
    name: "Kanban Board",
    description: "Multi-column workflow board with interactive drag-and-drop task routing and column counters.",
    category: "Files & Hierarchy",
    icon: Columns3,
    isNew: true,
  },
  {
    id: "drag-and-drop-list",
    name: "Drag-and-Drop List",
    description: "Interactive item reordering list with grip handles, keyboard step alternatives, and removal.",
    category: "Files & Hierarchy",
    icon: GripVertical,
    isNew: true,
  },
  {
    id: "task-board-card",
    name: "Task Board Card",
    description: "Workflow task card displaying priority badges, checklist counters, assignees, and due dates.",
    category: "Files & Hierarchy",
    icon: CheckSquare,
    isNew: true,
  },
  {
    id: "calendar-event-card",
    name: "Calendar Event Card",
    description: "Schedule appointment card with category palettes, virtual call links, attendees, and RSVP actions.",
    category: "Files & Hierarchy",
    icon: Calendar,
    isNew: true,
  },
  {
    id: "agenda-view",
    name: "Agenda View",
    description: "Chronological event schedule grouped by date with timeframe filters, time slots, and empty state.",
    category: "Scheduling & Workflows",
    icon: CalendarRange,
    isNew: true,
  },
  {
    id: "gantt-chart",
    name: "Gantt Chart",
    description: "Project roadmap timeline with configurable dependency curves, progress bars, and milestones.",
    category: "Scheduling & Workflows",
    icon: GanttChartSquare,
    isNew: true,
  },
  {
    id: "dependency-graph",
    name: "Dependency Graph",
    description: "Entity relationship topology map with cycle detection, orphan edge protection, and node selection.",
    category: "Scheduling & Workflows",
    icon: GitGraph,
    isNew: true,
  },
  {
    id: "flowchart-editor",
    name: "Flowchart Editor",
    description: "Editable process diagram builder with process, decision, and terminal nodes on a dot canvas grid.",
    category: "Scheduling & Workflows",
    icon: Workflow,
    isNew: true,
  },
  {
    id: "node-based-editor",
    name: "Node-Based Editor",
    description: "Visual node graph with typed I/O ports, bezier cables, keyboard movement, and connection routing.",
    category: "Scheduling & Workflows",
    icon: GitMerge,
    isNew: true,
  },
  {
    id: "workflow-builder",
    name: "Workflow Builder",
    description: "Multistep automation pipeline configuration with trigger, action, delay, and branch steps.",
    category: "Scheduling & Workflows",
    icon: Cpu,
    isNew: true,
  },
  {
    id: "chat-message",
    name: "Chat Message",
    description: "Individual conversation message with sender avatar, timestamp, status checkmarks, and attachments.",
    category: "Scheduling & Workflows",
    icon: MessageSquare,
    isNew: true,
  },
  {
    id: "chat-window",
    name: "Chat Window",
    description: "Full messaging interface with conversation stream, presence indicator, search filter, and composer.",
    category: "Scheduling & Workflows",
    icon: MessagesSquare,
    isNew: true,
  },
  {
    id: "chat-composer",
    name: "Chat Composer",
    description: "Message input bar with auto-resizing textarea, attachment chips, emoji shortcut, and send trigger.",
    category: "Scheduling & Workflows",
    icon: Send,
    isNew: true,
  },
  {
    id: "typing-indicator",
    name: "Typing Indicator",
    description: "Smooth bouncing dots presence indicator with bubble and text variants and reduced-motion fallback.",
    category: "Scheduling & Workflows",
    icon: MoreHorizontal,
    isNew: true,
  },
  {
    id: "conversation-list",
    name: "Conversation List",
    description: "Browse chats and channels with search filtering, unread badges, presence, and selection.",
    category: "Collaboration & DevTools",
    icon: MessagesSquare,
    isNew: true,
  },
  {
    id: "user-presence",
    name: "User Presence",
    description: "Configurable presence states (online, busy, away, offline, meeting) in badge, pill, and detailed modes.",
    category: "Collaboration & DevTools",
    icon: CircleDot,
    isNew: true,
  },
  {
    id: "video-call-controls",
    name: "Video Call Controls",
    description: "Meeting dock with mute, camera, screen-share, hand raise, and safe simulation indicators.",
    category: "Collaboration & DevTools",
    icon: Video,
    isNew: true,
  },
  {
    id: "activity-feed",
    name: "Activity Feed",
    description: "Chronological event timeline for commits, PR reviews, deployments, comments, and releases.",
    category: "Collaboration & DevTools",
    icon: Activity,
    isNew: true,
  },
  {
    id: "comment-thread",
    name: "Comment Thread",
    description: "Nested discussion threads with multi-level replies, inline editing, deletion, and reactions.",
    category: "Collaboration & DevTools",
    icon: MessageCircle,
    isNew: true,
  },
  {
    id: "review-feedback-panel",
    name: "Review / Feedback Panel",
    description: "Collect technical ratings and reviews with criteria breakdown, tags, and validation feedback.",
    category: "Collaboration & DevTools",
    icon: Star,
    isNew: true,
  },
  {
    id: "diff-viewer",
    name: "Diff Viewer",
    description: "Compare code or text changes cleanly with split side-by-side and unified inline modes.",
    category: "Collaboration & DevTools",
    icon: GitCompare,
    isNew: true,
  },
  {
    id: "terminal-emulator",
    name: "Terminal Emulator",
    description: "Interactive sandboxed terminal with safe built-in commands, history navigation, and ANSI styling.",
    category: "Collaboration & DevTools",
    icon: Terminal,
    isNew: true,
  },
  {
    id: "log-viewer",
    name: "Log Viewer",
    description: "Filter and inspect application logs with search, severity levels, auto-scroll, and metadata JSON.",
    category: "Collaboration & DevTools",
    icon: FileText,
    isNew: true,
  },
  {
    id: "json-viewer",
    name: "JSON Viewer",
    description: "Expandable/collapsible JSON tree inspector with syntax colors, search, and raw error handling.",
    category: "Collaboration & DevTools",
    icon: Braces,
    isNew: true,
  },
  {
    id: "api-request-builder",
    name: "API Request Builder",
    description: "Configure HTTP methods, endpoints, query params, headers, payload body, and authentication.",
    category: "API & Data Utilities",
    icon: Globe,
    isNew: true,
  },
  {
    id: "api-response-viewer",
    name: "API Response Viewer",
    description: "Inspect HTTP response status, latency, payload size, JSON body formatting, and headers table.",
    category: "API & Data Utilities",
    icon: Code2,
    isNew: true,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with flags, live match highlighting, capture groups, and presets.",
    category: "API & Data Utilities",
    icon: Search,
    isNew: true,
  },
  {
    id: "cron-expression-builder",
    name: "Cron Expression Builder",
    description: "Configure 5-part cron schedules with visual controls, human-readable explanations, and common presets.",
    category: "API & Data Utilities",
    icon: Clock,
    isNew: true,
  },
  {
    id: "query-builder",
    name: "Query Builder",
    description: "Construct database filters with condition groups (AND/OR), field operators, and SQL preview.",
    category: "API & Data Utilities",
    icon: Database,
    isNew: true,
  },
  {
    id: "formula-editor",
    name: "Formula Editor",
    description: "Spreadsheet-style formula bar with safe recursive evaluator (no eval), cell context, and syntax help.",
    category: "API & Data Utilities",
    icon: FunctionSquare,
    isNew: true,
  },
  {
    id: "spreadsheet-grid",
    name: "Spreadsheet Grid",
    description: "Editable spreadsheet grid with cell coordinates, keyboard navigation, and dynamic formula resolution.",
    category: "API & Data Utilities",
    icon: TableIcon,
    isNew: true,
  },
  {
    id: "chart-legend",
    name: "Chart Legend",
    description: "Toggle chart data series visibility with color swatches, metrics, and selection controls.",
    category: "API & Data Utilities",
    icon: Layers,
    isNew: true,
  },
  {
    id: "chart-crosshair-tooltip",
    name: "Chart Crosshair / Tooltip",
    description: "Interactive dual hairline crosshair tracking cursor coordinates with contextual data tooltip.",
    category: "API & Data Utilities",
    icon: Crosshair,
    isNew: true,
  },
  {
    id: "heatmap",
    name: "Heatmap",
    description: "2D intensity matrix mapping values to color ramps with cell inspection and min/max scale legend.",
    category: "API & Data Utilities",
    icon: LayoutGrid,
    isNew: true,
  },
  {
    id: "treemap",
    name: "Treemap",
    description: "Visualize hierarchical proportions accurately with nested squarified rectangles, labels, and drill-down.",
    category: "Visualizations & Mapping",
    icon: Layers,
    isNew: true,
  },
  {
    id: "sankey-diagram",
    name: "Sankey Diagram",
    description: "Visualize weighted flows between categories with smooth cubic Bézier ribbons and invalid link tolerance.",
    category: "Visualizations & Mapping",
    icon: GitMerge,
    isNew: true,
  },
  {
    id: "network-graph",
    name: "Network Graph",
    description: "Display connected entities with interactive draggable nodes, selection, zoom/pan, and node inspector.",
    category: "Visualizations & Mapping",
    icon: Network,
    isNew: true,
  },
  {
    id: "map-marker-cluster",
    name: "Map Marker / Cluster",
    description: "Group geographic points into proximity clusters across zoom levels with interactive pin details.",
    category: "Visualizations & Mapping",
    icon: MapPin,
    isNew: true,
  },
  {
    id: "onboarding-tour",
    name: "Onboarding Tour",
    description: "Step-by-step guided product walkthrough with spotlight targets, keyboard navigation, and completion state.",
    category: "Visualizations & Mapping",
    icon: Compass,
    isNew: true,
  },
  {
    id: "spotlight-search",
    name: "Spotlight Search",
    description: "Global command search palette (⌘K) with category filtering, keyboard navigation, and quick preview.",
    category: "Visualizations & Mapping",
    icon: Command,
    isNew: true,
  },
  {
    id: "application-search",
    name: "Application Search",
    description: "Unified search across all registered app content — styles, components, and pages — with text highlighting, category grouping, and keyboard navigation.",
    category: "Visualizations & Mapping",
    icon: Search,
    isNew: true,
  },
  {
    id: "permission-matrix",
    name: "Permission Matrix",
    description: "Configure roles, permissions, and access levels using an interactive RBAC grid with client sandbox declaration.",
    category: "Visualizations & Mapping",
    icon: ShieldCheck,
    isNew: true,
  },
  {
    id: "audit-log",
    name: "Audit Log",
    description: "Security and administrative audit trail with actor filtering, status filters, and changed state diff modal.",
    category: "Visualizations & Mapping",
    icon: FileText,
    isNew: true,
  },
  {
    id: "feature-flag-manager",
    name: "Feature Flag Manager",
    description: "Progressive delivery toggles by environment and audience group with rollout percentage sliders.",
    category: "Visualizations & Mapping",
    icon: SlidersHorizontal,
    isNew: true,
  },
  {
    id: "version-history",
    name: "Version History",
    description: "Compare revision differences with line diffs and safe functional rollback restoration.",
    category: "Visualizations & Mapping",
    icon: History,
    isNew: true,
  },
  {
    id: "design-token-editor",
    name: "Design Token Editor",
    description: "Edit colors, typography, spacing, and corner radii safely in a scoped sandbox with CSS export.",
    category: "Design System & a11y",
    icon: Palette,
    isNew: true,
  },
  {
    id: "responsive-preview-switcher",
    name: "Responsive Preview Switcher",
    description: "Preview components across mobile, tablet, and desktop viewports with device frames and orientation toggles.",
    category: "Design System & a11y",
    icon: Smartphone,
    isNew: true,
  },
  {
    id: "accessibility-audit-panel",
    name: "Accessibility Audit Panel",
    description: "Automated WCAG 2.1 rule checks and structured criteria for manual screen-reader testing.",
    category: "Design System & a11y",
    icon: ShieldAlert,
    isNew: true,
  },
  {
    id: "contrast-pair-tester",
    name: "Contrast Pair Tester",
    description: "Compare foreground and background colors with exact WCAG 2.1 relative luminance and compliance scoring.",
    category: "Design System & a11y",
    icon: Eye,
    isNew: true,
  },
  {
    id: "visual-regression-comparator",
    name: "Visual Regression Comparator",
    description: "Compare before-and-after screenshots with a draggable reveal slider, side-by-side mode, and onion-skin.",
    category: "Design System & a11y",
    icon: GitCompare,
    isNew: true,
  },
  {
    id: "live-component-playground",
    name: "Live Component Playground",
    description: "Expose supported component props, themes, and sizes safely without arbitrary code execution.",
    category: "Design System & a11y",
    icon: SlidersHorizontal,
    isNew: true,
  },
  {
    id: "component-dependency-graph",
    name: "Component Dependency Graph",
    description: "Visualize relationships between tokens, primitives, composites, and high-level features.",
    category: "Design System & a11y",
    icon: Network,
    isNew: true,
  },
  {
    id: "state-machine-visualizer",
    name: "State Machine Visualizer",
    description: "Finite state machine diagram with active node highlighting, event triggers, and transition log.",
    category: "Design System & a11y",
    icon: GitCommit,
    isNew: true,
  },
  {
    id: "mock-api-response-generator",
    name: "Mock API Response Generator",
    description: "Produce configurable sample API responses with realistic status codes, headers, and bodies.",
    category: "Design System & a11y",
    icon: FileJson,
    isNew: true,
  },
  {
    id: "form-validation-playground",
    name: "Form Validation Playground",
    description: "Test and inspect regex, password complexity, boundary clamping, and async validation rules in real-time.",
    category: "Design System & a11y",
    icon: ShieldCheck,
    isNew: true,
  },
  {
    id: "keyboard-shortcut-editor",
    name: "Keyboard Shortcut Editor",
    description: "Configure key bindings, verify conflict safety, and test keystrokes live.",
    category: "DevEx & Localization",
    icon: Keyboard,
    isNew: true,
  },
  {
    id: "theme-token-diff",
    name: "Theme Token Diff",
    description: "Compare two theme configurations and identify added, removed, and modified design tokens.",
    category: "DevEx & Localization",
    icon: GitCompare,
    isNew: true,
  },
  {
    id: "rtl-layout-preview",
    name: "RTL Layout Preview",
    description: "Preview components in Right-to-Left direction in a safe scoped sandbox without mutating global app state.",
    category: "DevEx & Localization",
    icon: Globe,
    isNew: true,
  },
  {
    id: "localization-preview",
    name: "Localization Preview",
    description: "Preview localized strings, native Intl date/currency formatting, and text expansion stress tests.",
    category: "DevEx & Localization",
    icon: Languages,
    isNew: true,
  },
  {
    id: "animation-timeline-editor",
    name: "Animation Timeline Editor",
    description: "Scrub animation timelines, adjust easing curves, and export CSS keyframe rules.",
    category: "DevEx & Localization",
    icon: Activity,
    isNew: true,
  },
  {
    id: "component-usage-analytics",
    name: "Component Usage Analytics",
    description: "Inspect component adoption counts, dominant variants, and prop distributions with honest telemetry framing.",
    category: "DevEx & Localization",
    icon: BarChart3,
    isNew: true,
  }
];

export type ComponentId = (typeof COMPONENTS_CATALOG)[number]["id"];
