import { buttonKit, type ButtonMode, type ButtonSlug } from "./kit";

export function buttonCode(slug: ButtonSlug, mode: ButtonMode) {
  const k = buttonKit(mode);
  const shell = (body: string) => `<!-- UI Hub Component Vault · ${slug} -->\n<div class="${k.canvas} isolate overflow-hidden rounded-2xl p-10">\n  ${body}\n</div>`;
  const snippets: Record<ButtonSlug, string> = {
    "corner-border": `<button class="group relative overflow-hidden bg-transparent px-7 py-3 font-semibold ${mode === "dark" ? "text-white" : "text-slate-950"}"><i class="absolute left-0 top-0 h-3 w-3 border-l-2 border-t-2 border-cyan-400 transition-all duration-300 group-hover:h-full group-hover:w-full"></i><i class="absolute bottom-0 right-0 h-3 w-3 border-b-2 border-r-2 border-violet-400 transition-all duration-300 group-hover:h-full group-hover:w-full"></i>Corner border</button>`,
    "corner-button": `<button class="relative bg-violet-600 px-7 py-3 font-bold text-white shadow-[6px_6px_0_#22d3ee] transition-all hover:translate-x-1 hover:translate-y-1 hover:shadow-[2px_2px_0_#22d3ee]">Corner button <span class="absolute -right-1 -top-1 h-3 w-3 bg-cyan-300"></span></button>`,
    "creepy-button": `<button class="group relative overflow-hidden rounded-full border border-rose-500/60 bg-black px-8 py-3 font-serif tracking-[.2em] text-rose-100"><span class="relative z-10">DON'T PRESS</span><span class="absolute inset-0 -translate-x-full bg-rose-700/50 transition-transform duration-500 group-hover:translate-x-0"></span><span class="absolute left-4 top-1/2 h-1.5 w-1.5 rounded-full bg-rose-300 opacity-0 shadow-[18px_0_0_#fda4af,36px_0_0_#fda4af] transition-opacity group-hover:opacity-100"></span></button>`,
    "radial-glow-button": `<button class="group relative overflow-hidden rounded-xl bg-slate-950 px-8 py-3 font-semibold text-white"><span class="absolute -inset-16 bg-[radial-gradient(circle_at_center,_#a855f7,transparent_55%)] opacity-0 blur-xl transition-opacity duration-300 group-hover:opacity-100"></span><span class="relative">Radial glow</span></button>`,
    "border-beam": `<button class="relative overflow-hidden rounded-xl p-px"><span class="absolute inset-[-100%] animate-[spin_3s_linear_infinite] bg-[conic-gradient(from_90deg,transparent_0_25%,#22d3ee_35%,transparent_45%)]"></span><span class="relative block rounded-[11px] bg-slate-950 px-7 py-3 text-white">Border beam</span></button>`,
    "glow-button": `<button class="rounded-xl bg-cyan-400 px-8 py-3 font-bold text-slate-950 shadow-[0_0_0_0_#22d3ee] transition-shadow duration-300 hover:shadow-[0_0_35px_8px_#22d3ee88]">Glow button</button>`,
    "marquee-hover": `<button class="group relative h-12 overflow-hidden rounded-full border border-violet-400 px-7 font-semibold"><span class="block transition-transform duration-300 group-hover:-translate-y-12">Explore</span><span class="absolute left-0 top-12 flex h-12 w-full items-center justify-center whitespace-nowrap text-violet-400 transition-transform duration-300 group-hover:-translate-y-12">Explore · Explore ·</span></button>`,
    "payment-transaction": `<button class="group flex items-center gap-3 rounded-xl bg-emerald-500 px-5 py-3 font-semibold text-emerald-950"><span class="grid h-6 w-6 place-items-center rounded-full bg-emerald-950 text-emerald-300 transition-transform group-hover:rotate-180">→</span><span>Pay $24.00</span><span class="max-w-0 overflow-hidden whitespace-nowrap transition-all duration-300 group-hover:max-w-20">Done ✓</span></button>`,
    "magic-card-effect": `<button class="group relative overflow-hidden rounded-2xl border border-violet-400/30 bg-slate-950 px-8 py-5 text-left text-white"><span class="absolute -left-12 -top-12 h-28 w-28 rounded-full bg-fuchsia-500/50 blur-2xl transition-all group-hover:left-20 group-hover:top-8"></span><span class="relative block text-xs text-violet-200">MAGIC CARD</span><span class="relative mt-1 block font-semibold">Hover for a spell</span></button>`,
    "rainbow-button": `<button class="group relative rounded-full bg-[linear-gradient(90deg,#f43f5e,#f59e0b,#eab308,#22c55e,#06b6d4,#8b5cf6,#ec4899)] bg-[length:200%_100%] px-8 py-3 font-bold text-white transition-all duration-500 hover:bg-right"><span class="rounded-full bg-black/20 px-1">Rainbow</span></button>`,
    "social-tooltip-hover-buttons": `<div class="flex gap-3"><button class="group relative grid h-11 w-11 place-items-center rounded-full bg-slate-950 text-white">𝕏<span class="absolute -top-9 scale-75 rounded bg-slate-950 px-2 py-1 text-xs opacity-0 transition group-hover:scale-100 group-hover:opacity-100">Twitter</span></button><button class="group relative grid h-11 w-11 place-items-center rounded-full bg-[#0a66c2] text-white">in<span class="absolute -top-9 scale-75 rounded bg-slate-950 px-2 py-1 text-xs opacity-0 transition group-hover:scale-100 group-hover:opacity-100">LinkedIn</span></button></div>`,
    "orbit-button": `<button class="group relative grid h-24 w-24 place-items-center rounded-full border border-cyan-300/50 text-xs font-bold text-cyan-300"><span class="absolute inset-[-7px] rounded-full border border-dashed border-violet-400 transition-transform duration-1000 group-hover:rotate-180"></span>ORBIT<span class="absolute -top-2 left-1/2 h-3 w-3 rounded-full bg-violet-400 shadow-[0_0_14px_#a78bfa]"></span></button>`,
    "galaxy-button": `<button class="group relative overflow-hidden rounded-full border border-white/20 bg-[#10082d] px-8 py-3 font-semibold text-white"><span class="absolute inset-0 bg-[radial-gradient(circle_at_20%_30%,#fff_0_1px,transparent_2px),radial-gradient(circle_at_70%_65%,#a855f7_0_1px,transparent_3px)] bg-[length:18px_18px] opacity-50 transition-transform duration-700 group-hover:scale-150"></span><span class="relative">Galaxy</span></button>`,
    "interactive-hover-button": `<button class="group flex items-center gap-3 rounded-xl bg-slate-950 px-6 py-3 font-semibold text-white"><span>Launch</span><span class="grid h-6 w-6 place-items-center rounded-full bg-white text-slate-950 transition-transform duration-300 group-hover:translate-x-2 group-hover:rotate-45">↗</span></button>`,
    "super-mario": `<button class="group relative border-4 border-slate-950 bg-red-500 px-7 py-3 font-bold uppercase text-white shadow-[5px_5px_0_#1e293b] transition-all hover:-translate-y-1 hover:bg-red-600 active:translate-y-1 active:shadow-none"><span class="mr-2 inline-block h-4 w-4 rounded-full border-2 border-white bg-red-500 group-hover:animate-bounce"></span>1-UP Start</button>`,
  };
  return shell(snippets[slug]);
}
