"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Check, GitBranch, Network, Send } from "lucide-react";
import { buttonKit, type ButtonMode, type ButtonSlug } from "./kit";

export function ButtonPreview({ slug, mode }: { slug: ButtonSlug; mode: ButtonMode }) {
  const k = buttonKit(mode);
  const wrap = (child: React.ReactNode) => <div className={`${k.canvas} isolate min-h-[260px] overflow-hidden rounded-2xl p-8`}><div className="flex min-h-[196px] items-center justify-center">{child}</div></div>;
  switch (slug) {
    case "corner-border": return wrap(<button className="group relative overflow-hidden bg-transparent px-7 py-3 font-semibold"><i className="absolute left-0 top-0 h-3 w-3 border-l-2 border-t-2 border-cyan-400 transition-all duration-300 group-hover:h-full group-hover:w-full" /><i className="absolute bottom-0 right-0 h-3 w-3 border-b-2 border-r-2 border-violet-400 transition-all duration-300 group-hover:h-full group-hover:w-full" />Corner border</button>);
    case "corner-button": return wrap(<motion.button whileTap={{ scale: .96 }} className="relative bg-violet-600 px-7 py-3 font-bold text-white shadow-[6px_6px_0_#22d3ee] transition-all hover:translate-x-1 hover:translate-y-1 hover:shadow-[2px_2px_0_#22d3ee]">Corner button<span className="absolute -right-1 -top-1 h-3 w-3 bg-cyan-300" /></motion.button>);
    case "creepy-button": return wrap(<button className="group relative overflow-hidden rounded-full border border-rose-500/60 bg-black px-8 py-3 font-serif tracking-[.2em] text-rose-100"><span className="relative z-10">DON&apos;T PRESS</span><span className="absolute inset-0 -translate-x-full bg-rose-700/50 transition-transform duration-500 group-hover:translate-x-0" /><span className="absolute left-4 top-1/2 h-1.5 w-1.5 rounded-full bg-rose-300 opacity-0 shadow-[18px_0_0_#fda4af,36px_0_0_#fda4af] transition-opacity group-hover:opacity-100" /></button>);
    case "radial-glow-button": return wrap(<button className="group relative overflow-hidden rounded-xl bg-slate-950 px-8 py-3 font-semibold text-white"><span className="absolute -inset-16 bg-[radial-gradient(circle_at_center,_#a855f7,transparent_55%)] opacity-0 blur-xl transition-opacity duration-300 group-hover:opacity-100" /><span className="relative">Radial glow</span></button>);
    case "border-beam": return wrap(<button className="relative overflow-hidden rounded-xl p-px"><motion.span animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 3, ease: "linear" }} className="absolute inset-[-100%] bg-[conic-gradient(from_90deg,transparent_0_25%,#22d3ee_35%,transparent_45%)]" /><span className="relative block rounded-[11px] bg-slate-950 px-7 py-3 text-white">Border beam</span></button>);
    case "glow-button": return wrap(<button className="rounded-xl bg-cyan-400 px-8 py-3 font-bold text-slate-950 shadow-[0_0_0_0_#22d3ee] transition-shadow duration-300 hover:shadow-[0_0_35px_8px_#22d3ee88]">Glow button</button>);
    case "marquee-hover": return wrap(<button className="group relative h-12 overflow-hidden rounded-full border border-violet-400 px-7 font-semibold"><span className="block transition-transform duration-300 group-hover:-translate-y-12">Explore</span><span className="absolute left-0 top-12 flex h-12 w-full items-center justify-center whitespace-nowrap text-violet-400 transition-transform duration-300 group-hover:-translate-y-12">Explore · Explore ·</span></button>);
    case "payment-transaction": return wrap(<PaymentButton />);
    case "magic-card-effect": return wrap(<button className="group relative overflow-hidden rounded-2xl border border-violet-400/30 bg-slate-950 px-8 py-5 text-left text-white"><span className="absolute -left-12 -top-12 h-28 w-28 rounded-full bg-fuchsia-500/50 blur-2xl transition-all duration-500 group-hover:left-20 group-hover:top-8" /><span className="relative block text-xs text-violet-200">MAGIC CARD</span><span className="relative mt-1 block font-semibold">Hover for a spell</span></button>);
    case "rainbow-button": return wrap(<button className="rounded-full bg-[linear-gradient(90deg,#f43f5e,#f59e0b,#eab308,#22c55e,#06b6d4,#8b5cf6,#ec4899)] bg-[length:200%_100%] px-8 py-3 font-bold text-white transition-all duration-500 hover:bg-right"><span className="rounded-full bg-black/20 px-1">Rainbow</span></button>);
    case "social-tooltip-hover-buttons": return wrap(<div className="flex gap-3"><Social icon={<GitBranch className="h-4 w-4" />} name="GitHub" dark /><Social icon={<Network className="h-4 w-4" />} name="LinkedIn" /><Social icon={<Send className="h-4 w-4" />} name="Telegram" cyan /></div>);
    case "orbit-button": return wrap(<button className="group relative grid h-24 w-24 place-items-center rounded-full border border-cyan-300/50 text-xs font-bold text-cyan-300"><span className="absolute inset-[-7px] rounded-full border border-dashed border-violet-400 transition-transform duration-1000 group-hover:rotate-180" />ORBIT<motion.span animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 3, ease: "linear" }} className="absolute inset-[-7px]"><span className="absolute -top-2 left-1/2 h-3 w-3 rounded-full bg-violet-400 shadow-[0_0_14px_#a78bfa]" /></motion.span></button>);
    case "galaxy-button": return wrap(<button className="group relative overflow-hidden rounded-full border border-white/20 bg-[#10082d] px-8 py-3 font-semibold text-white"><span className="absolute inset-0 bg-[radial-gradient(circle_at_20%_30%,#fff_0_1px,transparent_2px),radial-gradient(circle_at_70%_65%,#a855f7_0_1px,transparent_3px)] bg-[length:18px_18px] opacity-50 transition-transform duration-700 group-hover:scale-150" /><span className="relative">Galaxy</span></button>);
    case "interactive-hover-button": return wrap(<button className="group flex items-center gap-3 rounded-xl bg-slate-950 px-6 py-3 font-semibold text-white"><span>Launch</span><span className="grid h-6 w-6 place-items-center rounded-full bg-white text-slate-950 transition-transform duration-300 group-hover:translate-x-2 group-hover:rotate-45"><ArrowRight className="h-4 w-4" /></span></button>);
    case "super-mario": return wrap(<motion.button whileHover={{ y: -5 }} whileTap={{ y: 4 }} className="group relative border-4 border-slate-950 bg-red-500 px-7 py-3 font-bold uppercase text-white shadow-[5px_5px_0_#1e293b] active:shadow-none"><span className="mr-2 inline-block h-4 w-4 rounded-full border-2 border-white bg-red-500 group-hover:animate-bounce" />1-UP Start</motion.button>);
  }
}

function PaymentButton() { const [paid, setPaid] = useState(false); return <motion.button onClick={() => setPaid(true)} whileTap={{ scale: .97 }} className="group flex items-center gap-3 rounded-xl bg-emerald-500 px-5 py-3 font-semibold text-emerald-950"><span className="grid h-6 w-6 place-items-center rounded-full bg-emerald-950 text-emerald-300 transition-transform group-hover:rotate-180">{paid ? <Check className="h-4 w-4" /> : <ArrowRight className="h-4 w-4" />}</span><span>{paid ? "Payment complete" : "Pay $24.00"}</span></motion.button>; }
function Social({ icon, name, dark, cyan }: { icon: React.ReactNode; name: string; dark?: boolean; cyan?: boolean }) { return <button className={`group relative grid h-11 w-11 place-items-center rounded-full text-white ${dark ? "bg-slate-950" : cyan ? "bg-cyan-500" : "bg-[#0a66c2]"}`}>{icon}<span className="absolute -top-9 scale-75 rounded bg-slate-950 px-2 py-1 text-xs opacity-0 transition group-hover:scale-100 group-hover:opacity-100">{name}</span></button>; }
