import type { StyleMeta, StyleSlug } from "./types";

export const STYLE_LIST: StyleMeta[] = [
  {
    slug: "japandi",
    name: "Japandi",
    tagline: "Warm minimalism, quiet balance",
    description:
      "A serene fusion of Japanese and Scandinavian design. Warm neutrals, honest materials, thin 1px borders and generous whitespace — nothing extra, nothing missing.",
    tags: ["Warm neutrals", "Thin 1px borders", "Serif accents", "Whitespace", "No decoration"],
    palette: ["#F5F0E8", "#8B7355", "#3D3529", "#D8CBB6"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#F5F0E8", fg: "#3D3529", accent: "#8B7355", border: "#D8CBB6" },
  },
  {
    slug: "glassmorphism",
    name: "Glassmorphism",
    tagline: "Frosted glass, layered light",
    description:
      "Translucent frosted panels floating over vivid gradients. backdrop-blur, rgba borders and soft glows give interfaces a luminous sense of depth.",
    tags: ["Frosted blur", "RGBA borders", "Soft glow", "Purple & blue", "Depth"],
    palette: ["#8B5CF6", "#22D3EE", "#0B0A14", "#E0E7FF"],
    status: "live",
    defaultMode: "dark",
    tokens: { bg: "#0B0A14", fg: "#E0E7FF", accent: "#8B5CF6", border: "#22D3EE" },
  },
  {
    slug: "brutalist",
    name: "Brutalist",
    tagline: "Raw, loud, unapologetic",
    description:
      "Thick black borders, hard offset shadows, oversized impact type and zero decoration. Brutalism strips design down to structure and shouts with contrast.",
    tags: ["Border-4 black", "Hard shadows", "High contrast", "Raw layout", "Impact type"],
    palette: ["#000000", "#FFFFFF", "#FFDE00", "#FF3B30"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#FFFFFF", fg: "#000000", accent: "#FFDE00", border: "#000000" },
  },
  {
    slug: "minimalist",
    name: "Minimalist",
    tagline: "Less, but better",
    description:
      "Pure white space, a single muted accent and whisper-thin typography. Minimalism removes everything that is not the content itself.",
    tags: ["Pure white", "Single accent", "Thin type", "Max whitespace", "Zero decoration"],
    palette: ["#FFFFFF", "#111111", "#8A8A8A", "#F2F2F2"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#FFFFFF", fg: "#111111", accent: "#8A8A8A", border: "#F2F2F2" },
  },
  {
    slug: "neomorphism",
    name: "Neomorphism",
    tagline: "Soft UI, extruded surfaces",
    description:
      "Components appear pressed from the background itself — paired light and dark shadows on a same-hue canvas create a pillowy, tactile feel.",
    tags: ["Soft shadow pairs", "Same-hue bg", "No hard edges", "Muted palette", "Tactile"],
    palette: ["#E0E5EC", "#B8BEC7", "#FFFFFF", "#6D7DF2"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#E0E5EC", fg: "#5A6781", accent: "#6D7DF2", border: "#B8BEC7" },
  },
  {
    slug: "retro-y2k",
    name: "Retro / Y2K",
    tagline: "2000s chrome & candy",
    description:
      "Hot pink, electric blue and lime gradients. Bubbly type, star bursts, stickers, thick colorful borders and chaotic millennium-web joy.",
    tags: ["Hot gradients", "Bubble fonts", "Star bursts", "Chunky borders", "Chaotic fun"],
    palette: ["#FF2E93", "#00E5FF", "#B6FF00", "#7C4DFF"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#FF2E93", fg: "#FFFFFF", accent: "#B6FF00", border: "#00E5FF" },
  },
  {
    slug: "dark-tech",
    name: "Dark Tech",
    tagline: "Terminal glow, cyber precision",
    description:
      "Pure black canvases, phosphor-green monospace type, scanning grid lines and glowing borders — the interface as a machine.",
    tags: ["Pure black", "Mono type", "Neon glow", "Grid overlays", "Terminal UI"],
    palette: ["#000000", "#00FF41", "#00FFFF", "#111111"],
    status: "live",
    defaultMode: "dark",
    tokens: { bg: "#000000", fg: "#00FF41", accent: "#00FFFF", border: "#00FF41" },
  },
  {
    slug: "bento-grid",
    name: "Bento Grid",
    tagline: "Editorial grids, mixed sizes",
    description:
      "An asymmetric bento of mixed-size cards with subtle borders — the modern editorial layout popularized by Apple, Linear and Vercel.",
    tags: ["Asymmetric grid", "Mixed card sizes", "Subtle borders", "Editorial", "Modern"],
    palette: ["#0F172A", "#1E293B", "#94A3B8", "#6366F1"],
    status: "live",
    defaultMode: "dark",
    tokens: { bg: "#0F172A", fg: "#94A3B8", accent: "#6366F1", border: "#1E293B" },
  },
  {
    slug: "neobrutalist",
    name: "Neobrutalist",
    tagline: "Bold black borders, hard shadows, flat fills",
    description: "Bold black borders, hard shadows, bright flat fills, zero radius and unapologetic color.",
    tags: ["bold", "high-contrast", "playful", "raw"],
    palette: ["#FFE500", "#000000", "#FF5C00", "#FFFFFF"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#FFE500", fg: "#000000", accent: "#FF5C00", border: "#000000" },
  },
  {
    slug: "swiss",
    name: "Swiss Style",
    tagline: "Grid system, red accent, objective typography",
    description: "White background, vibrant Swiss red accents, strict 12-column grid structure, tight tracking and zero decoration.",
    tags: ["grid", "minimal", "red-accent", "editorial"],
    palette: ["#FFFFFF", "#E30613", "#111111", "#F4F4F4"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#FFFFFF", fg: "#111111", accent: "#E30613", border: "#E5E5E5" },
  },
  {
    slug: "editorial",
    name: "Editorial",
    tagline: "Cream paper, bold serif headlines, thin rules",
    description: "Cream background, high-contrast serif headlines, pull quotes, thin horizontal rules, and asymmetric layouts.",
    tags: ["serif", "journalism", "cream", "elegant"],
    palette: ["#FAF7F2", "#1C1917", "#78716C", "#D6D3D1"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#FAF7F2", fg: "#1C1917", accent: "#78716C", border: "#D6D3D1" },
  },
  {
    slug: "retro-futuristic",
    name: "Retro Futuristic",
    tagline: "80s grid horizon, synthwave neon, chrome glow",
    description: "Black canvas, chrome gradients, neon pink and cyan glows, 80s grid horizons and synthwave energy.",
    tags: ["synthwave", "neon", "cyber", "80s"],
    palette: ["#000000", "#FF00AA", "#00F0FF", "#1A0033"],
    status: "live",
    defaultMode: "dark",
    tokens: { bg: "#000000", fg: "#FFFFFF", accent: "#FF00AA", border: "#00F0FF" },
  },
  {
    slug: "bauhaus",
    name: "Bauhaus",
    tagline: "Primary geometry, form follows function",
    description: "Primary red, yellow and blue, geometric circles and triangles, and functional modernist layouts.",
    tags: ["primary-colors", "geometric", "art-history", "bold"],
    palette: ["#E63946", "#FFD60A", "#1D3557", "#F1FAEE"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#F1FAEE", fg: "#1D3557", accent: "#E63946", border: "#1D3557" },
  },
  {
    slug: "art-deco",
    name: "Art Deco",
    tagline: "Golden symmetry, geometric luxury, double rules",
    description: "Deep black canvas, metallic gold accents, geometric symmetry, and thin double-line borders.",
    tags: ["luxury", "gold", "symmetry", "vintage"],
    palette: ["#0A0A0A", "#C9A961", "#E5D2A0", "#1E1E1E"],
    status: "live",
    defaultMode: "dark",
    tokens: { bg: "#0A0A0A", fg: "#C9A961", accent: "#E5D2A0", border: "#C9A961" },
  },
  {
    slug: "material",
    name: "Material",
    tagline: "Layered paper cards, elevation shadows, ripples",
    description: "Google Material Design surfaces, elevation shadows, deep purple primary accent, and clean tactile cards.",
    tags: ["google", "shadows", "clean", "mobile-first"],
    palette: ["#FFFFFF", "#6200EE", "#03DAC6", "#121212"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#F5F5F5", fg: "#121212", accent: "#6200EE", border: "#E0E0E0" },
  },
  {
    slug: "monochromatic",
    name: "Monochromatic",
    tagline: "Single blue hue across every layer",
    description: "Harmonious interface built strictly from tint and shade variations of a single royal blue color.",
    tags: ["single-hue", "blue", "cohesive", "clean"],
    palette: ["#EFF6FF", "#2563EB", "#1E40AF", "#1E293B"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#EFF6FF", fg: "#1E293B", accent: "#2563EB", border: "#BFDBFE" },
  },
  {
    slug: "scandinavian",
    name: "Scandinavian",
    tagline: "Pale wood, soft sky blue, hygge warmth",
    description: "Pale wood tones, muted sky blue accents, generous airy whitespace, and soft rounded hygge comfort.",
    tags: ["hygge", "soft", "wood-tones", "minimal"],
    palette: ["#FDFBF7", "#E8DCC8", "#A8C0D6", "#334155"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#FDFBF7", fg: "#334155", accent: "#A8C0D6", border: "#E8DCC8" },
  },
  {
    slug: "modernist",
    name: "Modernist",
    tagline: "Mid-century geometry, asymmetric red pop",
    description: "Mid-century geometric balance, slate gray neutrals, off-white panels, and striking crimson red pops.",
    tags: ["mid-century", "asymmetric", "structured", "bold"],
    palette: ["#F3F4F6", "#1F2937", "#EF4444", "#E5E7EB"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#F3F4F6", fg: "#1F2937", accent: "#EF4444", border: "#E5E7EB" },
  },
  {
    slug: "organic",
    name: "Organic",
    tagline: "Earthy sage & terracotta, soft blob shapes",
    description: "Earthy sage green and warm sand tones, organic blob radii (rounded-[40%]), and hand-crafted warmth.",
    tags: ["earthy", "nature", "curved", "warm"],
    palette: ["#F7F5F0", "#A3B18A", "#DDB892", "#7F5539"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#F7F5F0", fg: "#7F5539", accent: "#A3B18A", border: "#DDB892" },
  },
  {
    slug: "luxury-minimal",
    name: "Luxury Minimal",
    tagline: "Deep black, refined gold, high fashion typography",
    description: "Ultra-dark obsidian surfaces, champagne gold hairline accents, extreme whitespace, and high fashion typography.",
    tags: ["high-fashion", "obsidian", "gold-hairline", "premium"],
    palette: ["#0A0A0A", "#B8935A", "#FFFFFF", "#171717"],
    status: "live",
    defaultMode: "dark",
    tokens: { bg: "#0A0A0A", fg: "#FFFFFF", accent: "#B8935A", border: "#262626" },
  },
  {
    slug: "neo-geo",
    name: "Neo-Geo",
    tagline: "90s Memphis patterns, playful geometric chaos",
    description: "90s Memphis pattern energy, hot pink, teal, yellow, and black geometric shapes in joyful chaos.",
    tags: ["memphis", "90s", "playful", "pattern"],
    palette: ["#FFF9E6", "#FF007A", "#00E5D1", "#FFD600"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#FFF9E6", fg: "#111111", accent: "#FF007A", border: "#111111" },
  },
  {
    slug: "kinetic",
    name: "Kinetic",
    tagline: "Motion-first energy, animated gradients, bold sans",
    description: "Motion-first interface energy, vibrant flowing gradients, sliding components, and contemporary pulse.",
    tags: ["animated", "high-energy", "gradient", "modern"],
    palette: ["#0F0C20", "#FF3366", "#7000FF", "#00F0FF"],
    status: "live",
    defaultMode: "dark",
    tokens: { bg: "#0F0C20", fg: "#FFFFFF", accent: "#FF3366", border: "#7000FF" },
  },
  {
    slug: "gradient-modern",
    name: "Gradient Modern",
    tagline: "Vibrant mesh gradients, soft glass blur, modern SaaS",
    description: "Rich mesh gradients in purple, pink and blue, translucent soft glass blur, and modern SaaS polish.",
    tags: ["saas", "mesh-gradient", "glass", "vibrant"],
    palette: ["#0D0B18", "#8B5CF6", "#EC4899", "#3B82F6"],
    status: "live",
    defaultMode: "dark",
    tokens: { bg: "#0D0B18", fg: "#FFFFFF", accent: "#EC4899", border: "#8B5CF6" },
  },
  {
    slug: "typography-first",
    name: "Typography First",
    tagline: "Oversized type is the design, tight tracking",
    description: "Type IS the design — oversized headlines, ultra-tight tracking, minimal chrome, and pure textual hierarchy.",
    tags: ["editorial-type", "oversized", "black-white", "stark"],
    palette: ["#FFFFFF", "#000000", "#555555", "#E5E5E5"],
    status: "live",
    defaultMode: "light",
    tokens: { bg: "#FFFFFF", fg: "#000000", accent: "#555555", border: "#000000" },
  },
  {
    slug: "metropolitan",
    name: "Metropolitan",
    tagline: "Urban dense grid, concrete slate, amber taxi glow",
    description: "Urban concrete grays, deep navy slate, and amber taxi highlights — high contrast city grid energy.",
    tags: ["urban", "dense-grid", "amber-glow", "architectural"],
    palette: ["#0F172A", "#1E293B", "#F59E0B", "#F8FAFC"],
    status: "live",
    defaultMode: "dark",
    tokens: { bg: "#0F172A", fg: "#F8FAFC", accent: "#F59E0B", border: "#334155" },
  },
];

export const STYLE_MAP: Record<StyleSlug, StyleMeta> = Object.fromEntries(
  STYLE_LIST.map((s) => [s.slug, s])
) as Record<StyleSlug, StyleMeta>;

export const LIVE_SLUGS: StyleSlug[] = STYLE_LIST.filter(
  (s) => s.status === "live"
).map((s) => s.slug);

export function getStyleMeta(slug: string): StyleMeta | undefined {
  return STYLE_MAP[slug as StyleSlug];
}
